[project]
name = "heal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "matplotlib>=3.10.3",
    "psutil>=7.0.0",
    "pyside6-fluent-widgets[full]>=1.8.1",
    "requests>=2.32.3",
]
