name: Windows
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
      
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - qt_ver: 6.5.3        
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_arch_install: msvc2019_64  
    env:
      targetName: Firefly-Launcher.exe
      fileName: Firefly-Launcher
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive
             
      - name: install env   
        env:
          archiveName: ${{ env.fileName }}-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}
          msvcArch: ${{ matrix.msvc_arch }}
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pip install "PySide6-Fluent-Widgets" -i https://pypi.org/simple/
          pip install PySide6==6.4.2
          pip install PySideSix-Frameless-Window>=0.3.1
          pip install pyinstaller

      - name: package  
        env:
          archiveName: ${{ env.fileName }}-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}
          msvcArch: ${{ matrix.msvc_arch }}          
        shell: pwsh
        run: |
          pyinstaller -w -i ./src/image/icon.ico ./main.py -n Firefly-Launcher
          xcopy /s /e /y src\qss\ dist\Firefly-Launcher\src\qss\
          xcopy /s /e /y src\image\ dist\Firefly-Launcher\src\image\
          xcopy /s /e /y src\patch\starrail\ dist\Firefly-Launcher\src\patch\starrail\
          xcopy /s /e /y src\patch\yuanshen\  dist\Firefly-Launcher\src\patch\yuanshen\
          xcopy /s /e /y src\patch\gradle\ dist\Firefly-Launcher\src\patch\gradle\
          xcopy /s /e /y src\patch\font\ dist\Firefly-Launcher\src\patch\font\
          xcopy /s /e /y config\ dist\Firefly-Launcher\config\
      
      - uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ env.fileName }}
          path: dist
